/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: "#630ed4",
        "background-light": "#FFFFFF",
        "background-dark": "#0A0A0B",
        "on-primary-fixed": "#25005a",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdcc6",
        "on-primary-fixed-variant": "#5a00c6",
        "surface-tint": "#732ee4",
        "secondary-container": "#c4a7ff",
        "surface-container-highest": "#e2e0fc",
        "on-surface-variant": "#4a4455",
        "on-tertiary-fixed-variant": "#713700",
        "on-secondary-fixed": "#25005a",
        "primary-fixed-dim": "#d2bbff",
        "on-secondary-container": "#523787",
        "on-tertiary-container": "#ffe0cd",
        "inverse-surface": "#2f2e43",
        "on-surface": "#1a1a2e",
        "on-secondary-fixed-variant": "#523787",
        "on-secondary": "#ffffff",
        "on-background": "#1a1a2e",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f2efff",
        "primary-container": "#7c3aed",
        "primary-fixed": "#eaddff",
        "surface-dim": "#dad7f3",
        "surface-container-high": "#e8e5ff",
        "secondary-fixed-dim": "#d2bbff",
        "outline-variant": "#ccc3d8",
        "surface-container": "#efecff",
        "tertiary": "#7d3d00",
        "error-container": "#ffdad6",
        "background": "#fcf8ff",
        "tertiary-container": "#a15100",
        "on-error": "#ffffff",
        "secondary": "#6a4fa0",
        "tertiary-fixed-dim": "#ffb784",
        "on-primary-container": "#ede0ff",
        "surface-container-low": "#f5f2ff",
        "inverse-primary": "#d2bbff",
        "outline": "#7b7487",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e0fc",
        "surface-bright": "#fcf8ff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#eaddff",
        "on-tertiary-fixed": "#301400",
        "surface": "#fcf8ff"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "8px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}
